compras/urls.py
from django.urls import path
from compras import views
from compras.views import FornecedorListView, FornecedorCreateView, FornecedorUpDateView, ComprasListView, ComprasCreateView, ComprasUpDateView, ComprasDeleteView


urlpatterns = [
                # Rotas para fornecedores
                path('fornecedores/', FornecedorListView.as_view(), name="fornecedor_list"),
                path('create_fornecedor/', FornecedorCreateView.as_view(), name="create_fornecedor"),
                path('update_fornecedor/<int:pk>', FornecedorUpDateView.as_view(), name="update_fornecedor"),

                # Rotas para compras
                path('compras/', ComprasListView.as_view(), name="compras_list"),
                path('create_compras/', ComprasCreateView.as_view(), name="create_compras"),
                path('update_compras/<int:pk>', ComprasUpDateView.as_view(), name="update_compras"),
                path('delete_compras/<int:pk>', ComprasDeleteView.as_view(), name='delete_compras'),
                path('compras/update-em-massa/', views.compras_update_em_massa, name='compras_update_em_massa'),
            ]

menu/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
# from menu.views import MenuListView
from .views import menu_view

# urlpatterns = [
#                 path('menu/', MenuListView.as_view(), name="menu"),
#                 path('create_payment/', MenuCreateView.as_view(), name="create_payment"),
#                 path('update_payment/<int:pk>', MenuUpDateView.as_view(), name="update_payment"),
#                 path('delete_payment/<int:pk>', MenuDeleteView.as_view(), name="delete_payment"),
#             ]

urlpatterns = [
    path('menu/', menu_view, name='menu'),
]


# urlpatterns = [
#     path('', menu_view, name='menu'),  # Acessível em /menu/?tenant=<nome_do_tenant>
# ]


# urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import logout
from django.shortcuts import redirect
from . import views
from django.conf import settings
from django.conf.urls.static import static

# http://127.0.0.1:8000/admin/?tenant=modelo_1
# http://127.0.0.1:8000/?tenant=modelo_1

# Função personalizada para logout
def custom_logout(request):
    logout(request)  # Encerra a sessão do usuário
    return redirect('home')  # Redireciona para a página de login

urlpatterns = [
                path('admin/', admin.site.urls),

                path('', views.home_view, name='home'),

                path('', include('users.urls')),
                path('', include('vendas.urls')),
                path('', include('funcionarios.urls')),
                path('', include('compras.urls')),
                path('', include('menu.urls')),
                path('', include('financeiro.urls')),
            ]

# Servindo arquivos de mídia em ambiente de desenvolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compras/models.py
from django.db import models
from users.models import Tenant
from django.conf import settings


class Fornecedor(models.Model):
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    nome_empresa = models.CharField(verbose_name="Fornecedor", max_length=50, blank=False)
    cnpj = models.CharField(verbose_name="CNPJ", max_length=14, null=True, blank=True)
    nome_contato = models.CharField(verbose_name="Contato", max_length=35, null=True, blank=True)
    telefone = models.CharField(verbose_name="Telefone", max_length=15, null=True, blank=True)
    email = models.CharField(verbose_name="E-mail", max_length=40, null=True, blank=True)
    endereco = models.CharField(verbose_name="Endereço", max_length=255, null=True, blank=True)
    cep = models.CharField(verbose_name="CEP", max_length=8, null=True, blank=True)
    numero = models.CharField(verbose_name="Número", max_length=10, null=True, blank=True)
    bairro = models.CharField(verbose_name="Bairro", max_length=20, null=True, blank=True)
    cidade = models.CharField(verbose_name="Cidade", max_length=30, null=True, blank=True)
    # author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False, default=1)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, blank=False, default=1)
    dt_atualizado = models.DateTimeField(auto_now=True, null=False, blank=False)

    # garantir que nome da empresa seja único para cada tenant
    class Meta:
        unique_together = ('tenant', 'nome_empresa')
        verbose_name = "Fornecedor"
        verbose_name_plural = "Fornecedores"

    def __str__(self):
        # Retorna uma string representando o fornecedor
        return f"{self.nome_empresa}"
        # return f"{self.nome_empresa} - {self.cnpj if self.cnpj else 'CNPJ não informado'}"

    
class Compras(models.Model):
    classificacao_choices = [
                        ('CMV', 'CMV'),
                        ('Gasto Fixo', 'Gasto Fixo'),
                        ('Gasto Variável', 'Gasto Variável')
                        ]
    tipo_pagamento = [
                    ('Dinheiro', 'Dinheiro'),
                    ('Cartão de Crédito', 'Cartão de Crédito'),
                    ('Cartão Débito', 'Cartão Débito'),
                    ('Pix', 'Pix'),
                    ('Cheque', 'Cheque'),
                    ('Transferência', 'Transferência'),
                    ('Boleto', 'Boleto'),
                    ('Débito em Conta', 'Débito em Conta')
    ]

    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    data_compra = models.DateField(verbose_name="Data da Venda", null=False, blank=False)
    data_vencimento = models.DateField(verbose_name="Data do Vencimento", null=True, blank=False)
    data_pagamento = models.DateField(verbose_name="Data do Pagamento", null=True, blank=True)
    # Chave estrangeira para Fornecedor, associando a PK de Fornecedor
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.PROTECT, verbose_name="Fornecedor", null=False, blank=False)
    valor_compra = models.DecimalField(verbose_name="Valor da Compra", max_digits=9, decimal_places=2, null=False, blank=False)
    valor_pago = models.DecimalField(verbose_name="Valor de Pagamento", max_digits=9, decimal_places=2, null=True, blank=True)
    qtd = models.CharField(verbose_name="Quantidade", max_length=10, null=True, blank=True)
    numero_boleto = models.CharField(verbose_name="Boleto", max_length=10, null=True, blank=True)
    grupo_produto = models.CharField(verbose_name="Grupo do Produto", max_length=20, null=True, blank=False)
    produto = models.CharField(verbose_name="Produto", max_length=20, null=True, blank=False)
    classificacao = models.CharField(verbose_name="Classificação", choices=classificacao_choices, max_length=20, null=True, blank=False)
    forma_pagamento = models.CharField(verbose_name="Forma de Pagamento", choices=tipo_pagamento, max_length=17, null=True, blank=False)
    observacao = models.CharField(verbose_name="Observação", max_length=35, null=True, blank=True)
    # author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False, default=1)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, blank=False, default=1)
    dt_atualizado = models.DateTimeField(auto_now=True, null=False, blank=False)

compras/views.py
# Bibliotecas padrão
import json
from decimal import Decimal
from datetime import datetime

# Bibliotecas de terceiros (Django)
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_protect
from django.core.serializers.json import DjangoJSONEncoder
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.decorators.cache import cache_page

# Importações locais (do meu projeto)
from .models import Fornecedor, Compras
from project.utils import generate_success_url
from project.mixins import TenantQuerysetMixin, HandleNoPermissionMixin


@csrf_protect
# Usado para atualizar (POST) os dados em massa da tabela de compras
def compras_update_em_massa(request):
    def parse_date(val):
        if val:
            try:
                return datetime.strptime(val, "%Y-%m-%d").date()
            except Exception:
                return None
        return None

    def parse_decimal(val):
        try:
            return Decimal(str(val)) if val not in [None, ""] else None
        except Exception:
            return None

    if request.method != "POST":
        return JsonResponse({"status": "error", "message": "Método não permitido"}, status=405)

    try:
        data = json.loads(request.body)
        updated_ids = []

        for row in data:
            if not row.get('id'):
                continue

            try:
                compra = Compras.objects.filter(tenant=request.user.tenant).get(pk=row['id'])

                # Datas
                compra.data_compra = parse_date(row.get('data_compra'))
                compra.data_vencimento = parse_date(row.get('data_vencimento'))
                compra.data_pagamento = parse_date(row.get('data_pagamento'))

                # Valores decimais
                compra.valor_compra = parse_decimal(row.get('valor_compra'))
                compra.valor_pago = parse_decimal(row.get('valor_pago'))

                # Campos textuais com default
                text_fields = [
                    'numero_boleto', 'classificacao', 'forma_pagamento',
                    'qtd', 'observacao', 'grupo_produto', 'produto'
                ]
                for field in text_fields:
                    setattr(compra, field, row.get(field, ""))

                # Fornecedor
                try:
                    compra.fornecedor = Fornecedor.objects.filter(tenant=request.user.tenant).get(pk=row['fornecedor']) if row.get('fornecedor') else None
                except Fornecedor.DoesNotExist:
                    compra.fornecedor = None

                compra.save()
                updated_ids.append(compra.id)

            except Compras.DoesNotExist:
                continue

        return JsonResponse({
            "status": "success",
            "updated_count": len(updated_ids),
            "updated_ids": updated_ids
        })

    except json.JSONDecodeError:
        return JsonResponse({"status": "error", "message": "JSON inválido"}, status=400)
    except Exception as e:
        return JsonResponse({"status": "error", "message": str(e)}, status=500)


class FornecedorListView(LoginRequiredMixin, PermissionRequiredMixin, TenantQuerysetMixin, HandleNoPermissionMixin, ListView):
    model = Fornecedor
    template_name = 'fornecedor_list.html'  # Garante que o template correto será usado
    permission_required = 'compras.view_fornecedor'  # Permissão para visualizar objetos'

    def get_queryset(self):
        # Obtém o tenant do usuário logado
        tenant = getattr(self.request.user, 'tenant', None)
        if not tenant:
            return Fornecedor.objects.none()  # Retorna vazio se o tenant não for encontrado

        # Filtra os fornecedores pelo tenant
        queryset = Fornecedor.objects.filter(tenant=tenant)

        # Captura os parâmetros da requisição GET
        nome_empresa = self.request.GET.getlist('nome_empresa[]')

        # Aplica o filtro de nome_empresa apenas se houver valores válidos
        nome_empresa = [nome for nome in nome_empresa if nome.strip()]  # Remove valores vazios e espaços
        if nome_empresa:
            queryset = queryset.filter(nome_empresa__in=nome_empresa)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Obter o tenant e adicionar ao contexto
        tenant = getattr(self.request.user, 'tenant', None)
        if tenant:
            tenant = str(tenant).lower().replace(' ', '_')
        context['tenant'] = tenant

        # Filtrar fornecedores pelo tenant
        fornecedores = Fornecedor.objects.filter(tenant=self.request.user.tenant).order_by('nome_empresa')
        nome_empresa = self.request.GET.getlist('nome_empresa[]')
        nome_empresa = [nome.strip() for nome in nome_empresa if nome.strip()]
        if nome_empresa:
            fornecedores = fornecedores.filter(nome_empresa__in=nome_empresa)

        # Adicionar paginação
        paginator = Paginator(fornecedores, 10)  # Define 10 itens por página
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        # Adicionar informações paginadas ao contexto
        context['fornecedor_list'] = page_obj

        # Adicionar o restante dos dados ao contexto
        context['fornecedores'] = fornecedores  # Lista completa para filtros
        context['numero_boleto'] = Compras.objects.filter(
            tenant=self.request.user.tenant
        ).values_list('numero_boleto', flat=True).distinct()

        return context
    

class FornecedorCreateView(LoginRequiredMixin, PermissionRequiredMixin, TenantQuerysetMixin, HandleNoPermissionMixin, CreateView):
    model = Fornecedor
    # campos que o usuario precisa preencher
    fields = ["nome_empresa", "cnpj", "nome_contato", "telefone", "email",
              "endereco", "cep", "numero", "bairro", "cidade"]
    # após o salvamentos redireciona para a view vendas
    success_url = reverse_lazy("fornecedor_list")
    permission_required = 'compras.add_fornecedor'

    def form_valid(self, form):
        # Certifique-se de que o tenant está sendo atribuído corretamente
        tenant = getattr(self.request.user, 'tenant', None)  # Busca o tenant associado ao usuário
        if not tenant:
            return self.form_invalid(form)  # Retorna erro se o tenant não for encontrado
        form.instance.tenant = tenant
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    # get_success_url é um método que retorna a URL de sucesso após a operação
    def get_success_url(self):
        tenant = getattr(self.request.user, 'tenant', None)
        return generate_success_url('fornecedor_list', tenant)


class FornecedorUpDateView(LoginRequiredMixin, PermissionRequiredMixin, TenantQuerysetMixin, HandleNoPermissionMixin, UpdateView):
    model = Fornecedor
    fields = ["nome_empresa", "cnpj", "nome_contato", "telefone", "email",
              "endereco", "cep", "numero", "bairro", "cidade"]
    success_url = reverse_lazy("fornecedor_list")
    permission_required = 'compras.change_fornecedor'  # Permissão para visualizar objetos'

    def get_success_url(self):
        tenant = getattr(self.request.user, 'tenant', None)
        return generate_success_url('fornecedor_list', tenant)


class ComprasListView(LoginRequiredMixin, PermissionRequiredMixin, TenantQuerysetMixin, HandleNoPermissionMixin, ListView):
    def compras_list(request):
        if not request.tenant:
            return render(request, 'error.html', {"message": "Tenant not found"})

    model = Compras
    permission_required = 'compras.view_compras'  # Permissão para visualizar objetos'

    def get_queryset(self):
        # Obtém o tenant do usuário logado
        tenant = getattr(self.request.user, 'tenant', None)
        if not tenant:
            return Compras.objects.none()  # Retorna vazio se o tenant não for encontrado
    
        # Filtra as compras pelo tenant
        queryset = Compras.objects.filter(tenant=tenant).order_by('data_compra')

        # Captura os parâmetros da requisição GET
        data_inicio = self.request.GET.get('data_inicio')
        data_fim = self.request.GET.get('data_fim')
        fornecedor_selecionado = self.request.GET.getlist('fornecedor[]')
        boleto_selecionado = self.request.GET.getlist('numero_boleto[]')
        filtro_data = self.request.GET.get('filtro_data', 'compra')  # Padrão é 'compra'

        # Aplica o filtro de datas conforme o radio selecionado
        if data_inicio:
            if filtro_data == 'vencimento':
                queryset = queryset.filter(data_vencimento__gte=data_inicio)
            elif filtro_data == 'pagamento':
                queryset = queryset.filter(data_pagamento__gte=data_inicio)
            else:
                queryset = queryset.filter(data_compra__gte=data_inicio)
        if data_fim:
            if filtro_data == 'vencimento':
                queryset = queryset.filter(data_vencimento__lte=data_fim)
            elif filtro_data == 'pagamento':
                queryset = queryset.filter(data_pagamento__lte=data_fim)
            else:
                queryset = queryset.filter(data_compra__lte=data_fim)

        # Aplica o filtro de fornecedor apenas se houver fornecedores selecionados e ignora valores vazios
        fornecedor_selecionado = [f for f in fornecedor_selecionado if f]  # Remove valores vazios
        if fornecedor_selecionado:  # Só aplica o filtro se a lista não estiver vazia
            queryset = queryset.filter(fornecedor__id__in=fornecedor_selecionado)

        boleto_selecionado = [b for b in boleto_selecionado if b]  # Remove valores vazios
        if boleto_selecionado:

compras/templates/compras/compras.html
{% load cache %}

<div class="container-fluid mb-3">
    {% cache 600 widget_compras %}
    <form action="" method="GET" class="d-flex align-items-center">
        <input type="hidden" name="tenant" value="{{ tenant }}">
        
        <div class="mb-2 me-2">
            <small for="data_inicio" class="form-text">Data Início:</small>
            <input type="date" class="form-control" id="data_inicio" name="data_inicio" value="{{ request.GET.data_inicio }}">
        </div>

        <div class="mb-2 ms-2 me-2">
            <small for="data_fim" class="form-text">Data Fim:</small>
            <input type="date" class="form-control" id="data_fim" name="data_fim" value="{{ request.GET.data_fim }}">
        </div>

        <div class="form-floating ms-2 me-2 mt-1">
            <select class="form-select" id="floatingSelect" name="fornecedor[]" aria-label="Floating label select example">
                <option value="">Selecione fornecedor</option>
                {% for fornecedor in fornecedores %}
                    <option value="{{ fornecedor.id }}" 
                        {% if fornecedor.id|stringformat:"s" in request.GET.fornecedor %}selected{% endif %}>
                        {{ fornecedor.nome_empresa }}
                    </option>
                {% endfor %}
            </select>
            <label for="floatingSelect">Fornecedor</label>
        </div>

        <div class="form-floating me-2 ms-2 mt-1">
            <select class="form-select" id="floatingSelect" name="numero_boleto[]" aria-label="Floating label select example">
                <option value="">Selecione boleto</option>
                {% for boleto in numero_boleto %}
                    <option value="{{ boleto }}" 
                        {% if boleto in request.GET.boleto %}selected{% endif %}>
                        {{ boleto }}
                    </option>
                {% endfor %}
            </select>
                <label for="floatingSelect">Boleto</label>
        </div>
    {% endcache %}
        <div class="mb-1 ms-1 mt-2">
            <button type="submit" class="btn btn-outline-primary me-2" name="buscar_compras">Buscar</button>
            <a href="{% url 'compras_list' %}?tenant={{ tenant }}" class="btn btn-outline-secondary me-2">Limpar</a>            
        
            {% if perms.comrpas.add_compras %}
                <a href="{% url 'create_compras' %}?tenant={{ tenant }}" class="btn btn-outline-success me-2">Nova Compra</a>
            {% else %}
                <a href="#" class="btn btn-outline-success btn-sm disabled">
                    <i class="fas fa-lock"></i>Nova Compra
                </a>
            {% endif %}
        </div>
    {% cache 7200 radio_compras %}
    <!-- Radios para filtrar datas compras - vencimento - pagamento -->
        <div class="mb-1 ms-2">
            <small for="filtro_data" class="form-text">Filtrar por data:</small>
            <fieldset class="mb-2 ms-0 mt-2 p-2 border rounded" style="min-width: 200px;">
                <legend class="float-none w-auto px-2" style="font-size: 1rem;">Filtrar datas</legend>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="filtro_data" id="filtro_data_compra" value="compra"
                        {% if request.GET.filtro_data == "compra" or not request.GET.filtro_data %}checked{% endif %}>
                    <label class="form-check-label" for="filtro_data_compra">Compra</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="filtro_data" id="filtro_data_pagamento" value="pagamento"
                    {% if request.GET.filtro_data == "pagamento" %}checked{% endif %}>
                    <label class="form-check-label" for="filtro_data_pagamento">Pagamento</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="filtro_data" id="filtro_data_vencimento" value="vencimento"
                        {% if request.GET.filtro_data == "vencimento" %}checked{% endif %}>
                    <label class="form-check-label" for="filtro_data_vencimento">Vencimento</label>
                </div>
            </fieldset>
        </div>
    {% endcache %}
    </form>
</div>

{% if compras_list %}
    <table class="table table-sm table-striped table-hover mt-3">
        <thead class="table-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Data Compra</th>
                <th scope="col">Vencimento</th>
                <th scope="col">Pagamento</th>
                <th scope="col">Fornecedor</th>
                <th scope="col">Valor Compra</th>
                <th scope="col">Valor Pago</th>
                <th scope="col">N° Boleto</th>
                <th scope="col">Grupo</th>
                <th scope="col">Produto</th>
                <th scope="col">Classificação</th>
                <th scope="col">Forma Pagamento</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for compras in compras_list %}
                <tr>
                    <th scope="row" >{{ compras.pk }}</th>
                    <td>{{ compras.data_compra| date:"d/m/y"}}</td>
                    <td>{{ compras.data_vencimento| date:"d/m/y"}}</td>
                    <td>{{ compras.data_pagamento| date:"d/m/y"}}</td>
                    <td>{{ compras.fornecedor }}</td>
                    <td>{{ compras.valor_compra| floatformat:2| default:"-" }}</td>
                    <td>{{ compras.valor_pago| floatformat:2| default:"-" }}</td>
                    <td>{{ compras.numero_boleto| default:"-" }}</td>
                    <td>{{ compras.grupo_produto| default:"-" }}</td>
                    <td>{{ compras.produto| default:"-" }}</td>
                    <td>{{ compras.classificacao| default:"-" }}</td>
                    <td>{{ compras.forma_pagamento| default:"-" }}</td>
                    <td>
                        {% if perms.compras.change_compras %}
                            <a href="{% url 'update_compras' pk=compras.pk %}?tenant={{ tenant }}" class="btn btn-outline-secondary btn-sm">Editar</a>
                        {% else %}
                            <a href="#" class="btn btn-outline-secondary btn-sm disabled" aria-disabled="true">
                                <i class="fas fa-lock"></i> Editar
                            </a>
                        {% endif %}

                        {% if perms.compras.delete_compras %}
                            <a href="{% url 'delete_compras' pk=compras.pk %}?tenant={{ tenant }}" class="btn btn-danger btn-sm">Excluir</a>
                        {% else %}
                            <a href="#" class="btn btn-danger btn-sm disabled" aria-disabled="true">
                                <i class="fas fa-lock"></i>Excluir
                            </a>
                        {% endif %}
                    </td>
                </tr>
                <tr class="detail-row" style="display: none;">
                    <td colspan="12">
                        <div class="detail-content">
                            <ul>
                                <li><strong>Quantidade:</strong> {{ compras.qtd|default:"-" }}</li>
                                <li><strong>Observação:</strong> {{ compras.observacao|default:"-" }}</li>
                                <li><strong>Autor:</strong> {{ compras.author.username|default:"-" }}</li>
                                <li><strong>Atualizado em:</strong> {{ compras.dt_atualizado|date:"d/m/y H:i" }}</li>
                            </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <style>
        .detail-row {
            background-color: #f9f9f9;
        }
        .detail-content {
            padding: 10px;
            margin-left: 20px;
        }
        .detail-content ul {
            list-style-type: none;
            padding-left: 0;
        }
        .detail-content ul li {
            margin-bottom: 5px;
        }
    </style>
    
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const rows = document.querySelectorAll("tbody tr:not(.detail-row)");
    
            rows.forEach(row => {
                row.addEventListener("click", function() {
                    const detailRow = this.nextElementSibling;
                    if (detailRow && detailRow.classList.contains("detail-row")) {
                        detailRow.style.display = detailRow.style.display === "none" ? "table-row" : "none";
                    }
                });
            });
        });
    </script>

{% else %}
    <div class="container">
        <div class="alert alert-warning mt-3" role="alert">
            Não há compras para o filtro selecionado.
        </div>
    </div>
{% endif %}

<!-- Paginação -->
<nav aria-label="Page navigation example">
<ul class="pagination justify-content-end">
    {% if compras_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?tenant={{ tenant }}&page={{ compras_list.previous_page_number }}">Previous</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link">Anterior</a>
        </li>
    {% endif %}
    
    {% for num in compras_list.paginator.page_range %}
        {% if compras_list.number == num %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">{{ num }}</span>
            </li>
        {% elif num > compras_list.number|add:-2 and num < compras_list.number|add:2 %}
            <li class="page-item">
                <a class="page-link" href="?tenant={{ tenant }}&page={{ num }}">{{ num }}</a>
            </li>
        {% endif %}
    {% endfor %}
    
    {% if compras_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?tenant={{ tenant }}&page={{ compras_list.next_page_number }}">Próxima</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link">Próxima</a>
        </li>
    {% endif %}
</ul>
</nav>
{% if perms.compras.add_compras %}
    {% include 'compras/compras_edicao.html' %}
{% endif %}

compras/templates/compras/compras_confirm_delete.html
{% extends 'global/base.html' %}

{% block page_title %}
    Excluir
{% endblock page_title %}

{% block content %}
    <h3>Excluir Compra</h3>

    <p>
        Tem certeza que deseja excluir a compra do dia 
        <strong>{{ compras.data_compra }}</strong> 
        do fornecedor 
        <strong>{{ compras.fornecedor }}</strong> 
        no valor de 
        <strong>{{ compras.valor_compra }}</strong>
        ?
    </p>

    <form method="POST">
        {% csrf_token %}

        <button type="submit" class="btn btn-danger">Excluir</button>
        <a href="{% url 'compras_list' %}?tenant={{ tenant }}" class="btn btn-primary">Cancelar</a>
    </form>
{% endblock content %}

compras/templates/compras/compras_form.html
{% extends 'global/base.html' %}
{% load crispy_forms_tags %}

{% block page_title %}
  {% if compras.pk %}
    Editar Compra
  {% else %}
    Nova Compra
  {% endif %}
{% endblock page_title %}


{% block content %}
  <!-- se eu tenho um id selecionado é porque estou realizando uma edição -->
  {% if compras.pk %}
    <h2>Editar Compras ID {{compras.pk}}</h2>
  {% else %}
    <h2>Nova Compra</h2>
  {% endif %}
    <form method="POST">
      <!-- para evitar o seguinte erro -> CSRF verification failed. Request aborted. -->
        {% csrf_token %}
      <!-- form faz aparecer o formulario já do Django -->
        {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Salvar</button>
      <a href="{% url 'compras_list' %}?tenant={{ tenant }}" class="btn btn-danger">Cancelar</a>
    </form>
{% endblock content %}