funcionarios/urls.py
from django.urls import path
from funcionarios.views import CadastroListView, CadastroCreateView, CadastroUpDateView, ContratacaoListView, ContratacaoCreateView, ContratacaoUpDateView, PagamentoListView, PagamentoCreateView, PagamentoUpDateView, RescisaoListView, RescisaoCreateView, RescisaoUpDateView, PagamentoDeleteView

urlpatterns = [
                # Rotas para Funcionários
                path('funcionario/', CadastroListView.as_view(), name="funcionarios_list"),
                path('create_funcionarios/', CadastroCreateView.as_view(), name="create_funcionarios"),
                path('update_funcionarios/<int:pk>', CadastroUpDateView.as_view(), name="update_funcionarios"),

                # Rotas para contratação de funcionarios
                path('contratacao/', ContratacaoListView.as_view(), name="contratacao_list"),
                path('create_contratacao/', ContratacaoCreateView.as_view(), name="create_contratacao"),
                path('update_contratacao/<int:pk>', ContratacaoUpDateView.as_view(), name="update_contratacao"),

                # Rotas para pagamento de funcionarios
                path('payment/', PagamentoListView.as_view(), name="pagamento_list"),
                path('create_payment/', PagamentoCreateView.as_view(), name="create_payment"),
                path('update_payment/<int:pk>', PagamentoUpDateView.as_view(), name="update_payment"),
                path('delete_payment/<int:pk>', PagamentoDeleteView.as_view(), name="delete_payment"),

                # Rotas para rescisao de funcionarios
                path('rescisao/', RescisaoListView.as_view(), name="rescisao_list"),
                path('create_rescisao/', RescisaoCreateView.as_view(), name="create_rescisao"),
                path('update_rescisao/<int:pk>', RescisaoUpDateView.as_view(), name="update_rescisao"),
            ]

menu/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
# from menu.views import MenuListView
from .views import menu_view

# urlpatterns = [
#                 path('menu/', MenuListView.as_view(), name="menu"),
#                 path('create_payment/', MenuCreateView.as_view(), name="create_payment"),
#                 path('update_payment/<int:pk>', MenuUpDateView.as_view(), name="update_payment"),
#                 path('delete_payment/<int:pk>', MenuDeleteView.as_view(), name="delete_payment"),
#             ]

urlpatterns = [
    path('menu/', menu_view, name='menu'),
]


# urlpatterns = [
#     path('', menu_view, name='menu'),  # Acessível em /menu/?tenant=<nome_do_tenant>
# ]


# urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import logout
from django.shortcuts import redirect
from . import views
from django.conf import settings
from django.conf.urls.static import static

# http://127.0.0.1:8000/admin/?tenant=modelo_1
# http://127.0.0.1:8000/?tenant=modelo_1

# Função personalizada para logout
def custom_logout(request):
    logout(request)  # Encerra a sessão do usuário
    return redirect('home')  # Redireciona para a página de login

urlpatterns = [
                path('admin/', admin.site.urls),

                path('', views.home_view, name='home'),

                path('', include('users.urls')),
                path('', include('vendas.urls')),
                path('', include('funcionarios.urls')),
                path('', include('compras.urls')),
                path('', include('menu.urls')),
                path('', include('financeiro.urls')),
            ]

# Servindo arquivos de mídia em ambiente de desenvolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

funcionarios/models.py
from django.conf import settings
from django.db import models
from users.models import Tenant
from django.core.exceptions import ValidationError


class Cadastro(models.Model):
    LIST_BANK = [('Banco do Brasil', 'Banco do Brasil'),
                   ('Banco Original', 'Banco Original'),
                   ('Bradesco', 'Bradesco'),
                   ('Caixa Econômica', 'Caixa Econômica'),
                   ('C6 Bank', 'C6 Bank'),
                   ('Itau', 'Itau'),
                   ('Inter', 'Inter'),
                   ('Neon', 'Neon'),
                   ('Next', 'Next'),
                   ('Nubank', 'Nubank'),
                   ('Santander', 'Santander'),
                   ]
    
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    nome_funcionario = models.CharField(verbose_name="Funcionário", max_length=40 , blank=False, unique=True)
    rg = models.CharField(verbose_name="RG", max_length=14, null=True , blank=True)
    cpf = models.CharField(verbose_name="CPF", max_length=14, null=True , blank=True)
    carteira_trabalho = models.CharField(verbose_name="CTPS", max_length=12, null=True, blank=True)
    endereco = models.CharField(verbose_name="Endereço", max_length=40, null=True, blank=True)
    numero = models.CharField(verbose_name="Número", max_length=255, null=True, blank=True)
    bairro = models.CharField(verbose_name="Bairro", max_length=20, null=True, blank=True)
    cidade = models.CharField(verbose_name="Cidade", max_length=30, null=True, blank=True)
    telefone = models.CharField(verbose_name="Telefone", max_length=13, null=True, blank=True)
    banco = models.CharField(verbose_name="Banco", choices=LIST_BANK, max_length=15, null=True, blank=True)
    agencia = models.CharField(verbose_name="Agencia", max_length=7, null=True, blank=True)
    conta = models.CharField(verbose_name="Conta", max_length=10, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, blank=False, default=1)
    dt_atualizado = models.DateTimeField(auto_now=True, null=False, blank=False)

    def __str__(self):
        # Retorna uma string representando o funcionário devido a ForeignKey em PG_Funcionarios
        return f"{self.nome_funcionario}"


class Contratacao(models.Model):
    CARGOS_POR_SETOR = {
                    'Administração': ["Gerente Financeiro", "Auxiliar Adm"],
                    'Cozinha': ["Chef", "Cozinheiro", "Cozinheiro Auxiliar"],
                    'Limpeza': ["Faxineira(o)"],
                    'Sushi': ["Peixeiro", "Sushiman", "Sushiman Auxiliar"],
                    'Salão': ["Caixa", "Cumin", "Garçom", "Gerente Geral", "Maitre", "Recepcionista"],
                    'Bar': ["Barman", "Copeiro"],
                    'Vallet': ["Manobrista"]
                    }
    
    SETOR_CHOICES = [(key, key) for key in CARGOS_POR_SETOR.keys()]
    CARGO_CHOICES = [(value, value) for sublist in CARGOS_POR_SETOR.values() for value in sublist]

    DOC_CONTABILIDADE = [('Enviado', 'Enviado'),
                         ('Não Enviado', 'Não Enviado')]

    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    nome_funcionario = models.ForeignKey(Cadastro, on_delete=models.PROTECT, verbose_name="Funcionário", null=False)
    setor = models.CharField(verbose_name="Setor", choices=SETOR_CHOICES, max_length=13, null=False, blank=False)
    cargo = models.CharField(verbose_name="Cargo", choices=CARGO_CHOICES, max_length=19, null=False, blank=False)
    data_exame_admissional = models.DateField(verbose_name="Dt Exame Admissional", null=True, blank=True)
    data_contratacao = models.DateField(verbose_name="Data Contratação", null=False, blank=False)
    salario = models.DecimalField(verbose_name="Salário", max_digits=9, decimal_places=2, null=True, blank=True)
    contabilidade_admissional = models.CharField(verbose_name="Doc Contabilidade", choices=DOC_CONTABILIDADE, max_length=11, null=True, blank=True)
    status_admissional = models.BooleanField(verbose_name="Status Rescisão", default=False)
    observacao_admissional = models.CharField(verbose_name="Obs Admissional", max_length=50, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, blank=False, default=1)
    dt_atualizado = models.DateTimeField(auto_now=True, null=False, blank=False)

    # Garantir que o funcionário não seja repetido para a mesma data de contratação
    class Meta:
        unique_together = ('nome_funcionario', 'data_contratacao')  # Um funcionário só pode ter uma contratação por data de pagamento

    @property
    def status_rescisao(self):
        """
        Verifica se há uma rescisão associada a esta contratação. 
        Estou usando status_rescisao em contratacao_list.html para ver se o funcionario esta ativo
        """
        return Rescisao.objects.filter(nome_funcionario_id=self.nome_funcionario_id).exists()

    def save(self, *args, **kwargs):
        # Lógica para determinar o status_admissional
        if (
            self.contabilidade_admissional == 'Enviado' and  # A coluna contabilidade_admissional deve ter o valor 'True'
            self.data_contratacao, self.data_exame_admissional is not None  # datas devem serem preenchidas
        ):
            self.status_admissional = True
        else:
            self.status_admissional = False

        super(Contratacao, self).save(*args, **kwargs)  # Chama o método save origina

    def __str__(self):
        # Retorna uma string representando o funcionário devido a ForeignKey em PG_Funcionarios
        return f"{self.nome_funcionario}"


class Rescisao(models.Model):
    LIST_CHOICES = [('Dispensa sem justa causa', 'Dispensa sem justa causa'),
                     ('Demissão por justa causa', 'Demissão por justa causa'),
                     ('Pedido de demissão','Pedido de demissão'),
                     ('Término do contrato', 'Término do contrato'),
                     ('Rescisão indireta', 'Rescisão indireta'),
                     ('Rescisão por culpa recíproca', 'Rescisão por culpa recíproca')
                     ]
    UNIFORME = [('Entregue', 'Entregue'),
                  ('Não Entregue', 'Não Entregue')
                  ]
    DOC_CONTABILIDADE = [('Enviado', 'Enviado'),
                         ('Não Enviado', 'Não Enviado')]
    
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    nome_funcionario = models.ForeignKey(Cadastro, on_delete=models.PROTECT, verbose_name="Funcionário", null=False)
    data_desligamento = models.DateField(verbose_name="Data Desligamento", null=False, blank=False)
    devolucao_uniforme = models.CharField(verbose_name="Devolução Uniforme", choices=UNIFORME, max_length=12, null=True, blank=True)
    data_exame_demissional = models.DateField(verbose_name="Data Exame Demissional", null=True, blank=True)
    data_homologacao = models.DateField(verbose_name="Data Homologação", null=True, blank=True)
    tipo_desligamento = models.CharField(verbose_name="Forma Desligamento", choices=LIST_CHOICES, max_length=30, null=False, blank=False)
    contabilidade_rescisao = models.CharField(verbose_name="Contabilidade Documentação", choices=DOC_CONTABILIDADE, max_length=11, null=True, blank=True)
    observacao_demissional = models.CharField(verbose_name="Observação", max_length=40, null=True, blank=True)
    status_rescisao = models.BooleanField(verbose_name="Status Rescisão", default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, blank=False, default=1)
    dt_atualizado = models.DateTimeField(auto_now=True, null=False, blank=False)

    # Garantir que o funcionário não seja repetido para a mesma data de contratação
    class Meta:
        unique_together = ('nome_funcionario', 'data_desligamento')  # Um funcionário só pode ter uma contratação por data de pagamento


    def save(self, *args, **kwargs):
        # Lógica para determinar o status_rescisao
        if (
            self.devolucao_uniforme == 'Entregue' and  # A coluna devolucao_uniforme deve ter o valor 'True'
            self.data_exame_demissional is not None and  # data_exame_demissional deve ser preenchida
            self.contabilidade_rescisao == 'Enviado'  # A coluna contabilidade_rescisao deve ter o valor 'True'
        ):
            self.status_rescisao = True
        else:
            self.status_rescisao = False

        super(Rescisao, self).save(*args, **kwargs)  # Chama o método save origina


class Pagamento(models.Model):
    lista_tipo_pagamento = [
                            ('Salário', 'Salário'),
                            ('Adiantamento', 'Adiantamento'),
                            ('Vale', 'Vale'),
                            ('Vale Transporte', 'Vale Transporte'), 
                            ('Extra', 'Extra'),
                            ('Rescisão', 'Rescisão'),
                            ('Comissão', 'Comissão'),
                            ('Férias', 'Férias'),
                            ('13° Salário', '13° Salário')
                            ]
    lista_forma_pagamento = [
                             ('Conta Salário', 'Conta Salário'),
                             ('Dinheiro', 'Dinheiro'),
                             ('Transferência', 'Transferência'),
                             ('Pix', 'Pix'),
                             ('Cheque', 'Cheque'),
                             ('Multa Recisória', 'Multa Recisória')
                             ]
    
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    # Chave estrangeira para Funcionario, associando a PK de nome
    nome_funcionario = models.ForeignKey(Cadastro, on_delete=models.PROTECT, verbose_name="Funcionário", null=False)

funcionarios/templates/funcionarios/contratacao.html
{% load cache %}


<div class="container-fluid">
    <form id="filtro-form" action="" method="GET" class="d-flex align-items-center">
    {% cache 7200 widget_contratacao %}
        <input type="hidden" name="tenant" value="{{ tenant }}">
        <div class="mb-2">
            <small for="data_inicio" class="form-text">Contratação Início:</small>
            <input type="date" class="form-control" id="data_inicio_contratacao" name="data_inicio_contratacao" value="{{ request.GET.data_contratacao }}">
        </div>
        <div class="mb-2 ms-2 me-2">
            <small for="data_fim" class="form-text">Contratação Fim:</small>
            <input type="date" class="form-control" id="data_fim_contratacao" name="data_fim_contratacao" value="{{ request.GET.data_contratacao }}">
        </div>
        <div class="form-floating mb-2 ms-2 me-2 mt-2">
            <select class="form-select" id="floatingSelect" name="nome_funcionario" aria-label="Floating label select example">
                <option value="">Selecione funcionário</option>
                {% for funcionario in contratacao_funcionarios %}
                    <option value="{{ funcionario.id }}" 
                        {% if funcionario.id|stringformat:"s" == request.GET.nome_funcionario %} selected {% endif %}>
                        {{ funcionario.nome_funcionario }}
                    </option>
                {% endfor %}
            </select>
            <label for="floatingSelect">Funcionáro</label>
        </div>
        <div class="form-floating mb-1 ms-2 me-2 mt-2">
            <select class="form-select" id="floatingSelect" name="setor" aria-label="Floating label select example">
                <option value="">Selecione setor</option>
                {% for setor in contratacao_setor %}
                    <option value="{{ setor }}" 
                        {% if setor|stringformat:"s" == request.GET.setor %} selected {% endif %}>
                        {{ setor }}
                    </option>
                {% endfor %}
            </select>
            <label for="floatingSelect">Setor</label>
        </div>
        <div class="form-floating mb-1 ms-2 me-2 mt-2">
            <select class="form-select" id="floatingSelect" name="cargo" aria-label="Floating label select example">
                <option value="">Selecione cargo</option>
                {% for cargo in contratacao_cargo %}
                    <option value="{{ cargo }}"
                        {% if cargo|stringformat:"s" == request.GET.cargo %} selected {% endif %}>
                        {{ cargo }}
                    </option>
                {% endfor %}
            </select>
            <label for="floatingSelect">Cargo</label>
        </div>
    {% endcache %}
        <div class="mb-1 ms-2 mt-2">
            <button type="submit" class="btn btn-outline-primary me-2" name="buscar_funcionario_cadastro">Buscar</button>
            <a href="{% url 'contratacao_list' %}?tenant={{ tenant }}" class="btn btn-outline-secondary me-2">Limpar</a>
            
            {% if perms.funcionarios.add_contratacao %}
                <a href="{% url 'create_contratacao' %}?tenant={{ tenant }}" class="btn btn-outline-success me-2">Contratar</a>
            {% else %}
                <a class="btn btn-outline-success disabled" href="#" aria-disabled="true">Contratar</a>
            {% endif %}
        </div>
        <!-- switch para filtrar contratos ativos -->
        <div class="form-check form-switch mb-2 me-2 ms-2 mt-3">
            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" name="filtrar_status_contrato" {% if filtrar_status_contrato %}checked{% endif %} onchange="document.getElementById('filtro-form').submit();">
            <label class="form-check-label" for="flexSwitchCheckDefault">Contratos ativos</label>
        </div>
    </form>
</div>

{% if contratacao_list %}
    <table class="table table-sm table-striped table-hover mt-3">
        <thead class="table-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Setor</th>
                <th scope="col">Cargo</th>
                <th scope="col">Exame</th>
                <th scope="col">Contratação</th>
                <th scope="col">Salário</th>
                <th scope="col">Doc Contabilidade</th>
                <th scope="col">Observação</th>
                <th scope="col">Contrato</th>
                <th scope="col">Status</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for contratacao in contratacao_list %}
                <tr>
                    <th scope="row" >{{ contratacao.pk }}</th>
                    <td>{{ contratacao.nome_funcionario }}</td>
                    <td>{{ contratacao.setor| default:"-" }}</td>
                    <td>{{ contratacao.cargo| default:"-" }}</td>
                    <td>{{ contratacao.data_exame_admissional|date:"d/m/y"}}</td>
                    <td>{{ contratacao.data_contratacao|date:"d/m/y" }}</td>
                    <td>{{ contratacao.salario| default:"-" }}</td>
                    <td>{{ contratacao.contabilidade_admissional| default:"-" }}</td>
                    <td>{{ contratacao.observacao_admissional| default:"-" }}</td>
                    <td>
                        {% if contratacao.status_rescisao == False %}
                            <span class="badge bg-success">Ativo</span>
                        {% else %}
                            <span class="badge bg-danger">Rescindido</span>
                        {% endif %}
                    </td>
                    <td>
                        <span 
                            class="btn btn-sm 
                            {% if contratacao.contabilidade_admissional != "Enviado" or contratacao.data_exame_admissional == None %}
                                btn-danger
                            {% else %}
                                btn-success
                            {% endif %}"
                            >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span>
                    </td>
                    <td>
                        {% if perms.funcionarios.change_contratacao %}
                            <a href="{% url 'update_contratacao' pk=contratacao.pk %}?tenant={{ tenant }}" class="btn btn-outline-secondary btn-sm">Editar</a>
                        {% else %}
                            <a class="btn btn-outline-secondary disabled"  href="#" aria-disabled="true">Editar</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <!-- Paginação -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            {% if contratacao_funcionarios_paginados.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?tenant={{ tenant }}&page={{ contratacao_funcionarios_paginados.previous_page_number }}">Anterior</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Anterior</a>
                </li>
            {% endif %}

            {% for num in contratacao_funcionarios_paginados.paginator.page_range %}
                {% if contratacao_funcionarios_paginados.number == num %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% elif num > contratacao_funcionarios_paginados.number|add:-2 and num < contratacao_funcionarios_paginados.number|add:2 %}
                    <li class="page-item">
                        <a class="page-link" href="?tenant={{ tenant }}&page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if contratacao_funcionarios_paginados.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?tenant={{ tenant }}&page={{ contratacao_funcionarios_paginados.next_page_number }}">Próxima</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Próxima</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% else %}
    <div class="container">
        <div class="alert alert-warning mt-3" role="alert">
            Não há registros para esse filtro.
        </div>
    </div>
{% endif %}

funcionarios/templates/funcionarios/contratacao_list.html
{% extends 'global/base.html' %}

{% block page_title %}
    Funcionário
{% endblock page_title %}

{% block content %}
    <h5 class="mb-4 mt-3">Contratação de Funcionário</h5>
    {% include 'funcionarios/contratacao.html' %}
{% endblock content %}

funcionarios/templates/funcionarios/pagamento.html
{% load cache %}

<div class="container-fluid">
    <form action="" method="GET" class="d-flex align-items-center">
        {% cache 600 widget_pagamento %}
        <input type="hidden" name="tenant" value="{{ tenant }}">
        
        <div class="mb-2 me-2">
            <small for="data_inicio" class="form-text">Data Início:</small>
            <input type="date" class="form-control" id="data_inicio_pagamento_funcionario" name="data_inicio_pagamento_funcionario" value="{{ request.GET.data_inicio_pagamento_funcionario }}">
        </div>

        <div class="mb-2 ms-2 me-2">
            <small for="data_fim" class="form-text">Data Fim:</small>
            <input type="date" class="form-control" id="data_fim_pagamento_funcionario" name="data_fim_pagamento_funcionario" value="{{ request.GET.data_fim_pagamento_funcionario }}">
        </div>

        <div class="form-floating mb-2 ms-2 me-2 mt-2">
            <select class="form-select" id="floatingSelect" name="nome_funcionario" aria-label="Floating label select example">
                <option value="">Selecione todos funcionário</option>
                {% for funcionario in pagamento_funcionarios %}
                    <option value="{{ funcionario.nome_funcionario_id}}" 
                        {% if funcionario.nome_funcionario_id|stringformat:"s" == request.GET.nome_funcionario %} selected {% endif %}>
                        {{ funcionario.nome_funcionario__nome_funcionario }}
                    </option>
                {% endfor %}
            </select>
            <label for="floatingSelect">Funcionário</label>
        </div>
        
        <div class="form-floating mb-2 ms-2 me-2 mt-2">
            <select class="form-select" id="floatingSelectTipoPagamento" name="tipo_pagamento" aria-label="Floating label select example">
                <option value="">Selecione tipo de pagamento</option>
                {% for tipo in tipos_pagamento %}
                    <option value="{{ tipo }}" 
                        {% if tipo|stringformat:"s" == request.GET.tipo_pagamento %} selected {% endif %}>
                        {{ tipo }}
                    </option>
                {% endfor %}
            </select>
            <label for="floatingSelectTipoPagamento">Tipo de Pagamento</label>
        </div>
        {% endcache %}
        <div class="mb-2 ms-2 mt-3">
            <button type="submit" class="btn btn-outline-primary me-2" name="buscar_funcionario_pagamento">Buscar</button>
            <a href="{% url 'pagamento_list' %}?tenant={{ tenant }}" class="btn btn-outline-secondary me-2">Limpar</a>
            {% if perms.funcionarios.add_pagamento %}
                <a href="{% url 'create_payment' %}?tenant={{ tenant }}" class="btn btn-outline-success me-2">Pagar Funcionário</a>
            {% else %}
                <a class="btn btn-outline-success disabled me-2" href="#" aria-disabled="true">Pagar Funcionário</a>
            {% endif %}
        </div>
    </form>
</div>

{% if pagamento_list %}
    <div class="table-responsive mt-3">
        <table class="table table-sm table-striped table-hover"> <!-- table-bordered -->
            <thead class="table-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Data Pagamento</th>
                    <th scope="col">Valor Pago</th>
                    <th scope="col">Tipo Pagamento</th>
                    <th scope="col">Forma Pagamento</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for pagamento in pagamento_list %}
                    <tr>
                        <th scope="row" >{{ pagamento.pk }}</th>
                        <td>{{ pagamento.nome_funcionario }}</td>
                        <td>{{ pagamento.data_pagamento|date:"d/m/y"|default:"-" }}</td>
                        <td>{{ pagamento.valor_pago|default:"-" }}</td>
                        <td>{{ pagamento.tipo_pagamento|default:"-" }}</td>
                        <td>{{ pagamento.forma_pagamento|default:"-" }}</td>
                        <td>
                            {% if perms.funcionarios.change_pagamento %}
                                <a href="{% url 'update_payment' pk=pagamento.pk %}?tenant={{ tenant }}" class="btn btn-outline-secondary btn-sm">Editar</a>
                            {% else %}
                                <a class="btn btn-outline-secondary disabled btn-sm" href="#" aria-disabled="true">Editar</a>
                            {% endif %}

                            {% if perms.funcionarios.delete_pagamento %}
                                <a href="{% url 'delete_payment' pk=pagamento.pk %}?tenant={{ tenant }}" class="btn btn-outline-danger btn-sm">Excluir</a>
                            {% else %}
                                <a class="btn btn-outline-danger disabled btn-sm" href="#" aria-disabled="true">Excluir</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- Paginação -->
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    {% if pagamento_funcionarios_paginados.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?tenant={{ tenant }}&page={{ pagamento_funcionarios_paginados.previous_page_number }}">Anterior</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Anterior</a>
                    </li>
                    {% endif %}

                    {% for num in pagamento_funcionarios_paginados.paginator.page_range %}
                    {% if pagamento_funcionarios_paginados.number == num %}
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">{{ num }}</span>
                    </li>
                    {% elif num > pagamento_funcionarios_paginados.number|add:-2 and num < pagamento_funcionarios_paginados.number|add:2 %}
                    <li class="page-item">
                        <a class="page-link" href="?tenant={{ tenant }}&page={{ num }}">{{ num }}</a>
                    </li>
                    
                    {% endif %}
                    {% endfor %}

                    {% if pagamento_funcionarios_paginados.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?tenant={{ tenant }}&page={{ pagamento_funcionarios_paginados.next_page_number }}">Próxima</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Próxima</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
    </div>
{% else %}
    <div class="container">
        <div class="alert alert-warning mt-3" role="alert">
            Não há pagamentos para o filtro selecionado.
        </div>
    </div>
{% endif %}